spring.application.name=smartinventory

spring.datasource.url=jdbc:postgresql://localhost:5432/smartinventory
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=none

